# Generated by Django 4.0.3 on 2022-04-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.IntegerField(help_text='ID : ', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='NAME : ', max_length=50)),
                ('address', models.CharField(help_text='ADDRESS : ', max_length=50)),
            ],
        ),
    ]
