# Generated by Django 4.0.3 on 2022-04-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_3', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['id']},
        ),
    ]
