# Generated by Django 4.0.3 on 2022-03-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('area', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('fullName', models.CharField(max_length=50)),
                ('contactAddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person2',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('contactAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
