# Generated by Django 4.0.3 on 2022-04-04 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2_1', '0002_model1_model2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='model1',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app2_1.place')),
                ('name', models.CharField(max_length=50)),
                ('momo', models.BooleanField(default=True)),
            ],
        ),
    ]
