# Generated by Django 4.0.3 on 2022-04-05 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2_1', '0003_model3_place_alter_model1_options_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name', '-id']},
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Enter name of place', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='momo',
            field=models.BooleanField(default=True, help_text='Serve MoMo'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(help_text='Enter Restaurent Name ', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place',
            field=models.OneToOneField(help_text='Select Location', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app2_1.place'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2_1.restaurant')),
            ],
            options={
                'ordering': ['restaurant', 'name', 'email', 'phone'],
            },
        ),
    ]
