# Generated by Django 4.0.3 on 2022-04-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_1', '0006_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Article',
        ),
    ]
