# Generated by Django 4.0.3 on 2022-04-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_1', '0007_rename_news_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['cid']},
        ),
    ]
