# Generated by Django 4.0.3 on 2022-04-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_1', '0008_delete_person_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('fullName', models.CharField(max_length=50)),
                ('contactAddress', models.CharField(max_length=50)),
                ('photograph', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['pid'],
            },
        ),
    ]
